DEFINE BOX #parabox size (5, 5)
DEFINE BOX #receiver size (3, 3)
DEFINE INFINITY #infinity ref #parabox
DEFINE WALL #wall

PLACE #infinity at (1, 2) in #parabox
PLACE #receiver at (2, 2) in #parabox
PLACE #wall at (3, 2) in #parabox

// 1/10 -> 0/3
// 3/10 -> 0/3
// 5/10 -> 1/3
// 7/10 -> 2/3
// 9/10 -> 2/3

PLACE #parabox at (4, 0) in #parabox
PUSH #parabox east MOVED
EXPECT #parabox at (0, 0) in #receiver

PLACE #parabox at (4, 1) in #parabox
PUSH #parabox east MOVED
EXPECT #parabox at (0, 0) in #receiver

PLACE #parabox at (4, 2) in #parabox
PUSH #parabox east MOVED
EXPECT #parabox at (0, 1) in #receiver

PLACE #parabox at (4, 3) in #parabox
PUSH #parabox east MOVED
EXPECT #parabox at (0, 2) in #receiver

PLACE #parabox at (4, 4) in #parabox
PUSH #parabox east MOVED
EXPECT #parabox at (0, 2) in #receiver
