[package]
name = "parabox-tests"
version.workspace = true
edition.workspace = true

[dependencies]
parabox = { workspace = true }
parabox-parser = { workspace = true }
parabox-macros = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
